### ISSUE TITLE
Cómo reportar errores en los datos al Gobierno de La Rioja

### ISSUE THREAD

**Issue by goiblas** [goiblas/open-data-la-rioja#17]
Al trabajar con los datos del portal del Gobierno de La Rioja, me he encontrado con algunos errores en los datos.

Ejemplo: [Flujo de inmigración interior por año, Comunidad Autónoma de origen y sexo](https://web.larioja.org/dato-abierto/datoabierto?n=opd-329) 
- Tiene datos hasta el año 2040

¿Cómo se pueden reportar este tipo de errores al Gobierno de La Rioja?

**Comment by Gabriel-ghub** [comment]
Jesús, hola!

Estuve viendo este tema, y en la web de dato abierto, tienen un formulario para reportar problemas.
Valdrá con esto? O igual es necesario llamar y preguntar, si es así, no tengo problema en hacerlo.

Pero con intentar con el formulario, igual tenemos suerte 🤞

![image](https://github.com/user-attachments/assets/78a7f46d-d13c-4855-a624-6f59a5e304aa)

**Comment by goiblas** [comment]
No recuerdo ese formulario, quizás es reciente, voy a probar a comunicar los errores desde ese formulario, gracias!
Mantengo la issue abierta y comparto si recibo respuesta

**Comment by goiblas** [comment]
He recibido contestación, y me han dado un correo al que reportar errores y hacer consultas, así que cualquier error o consulta con los datos, abrir una nueva issue o enviármela por correo y se la hago llegar
