### ISSUE TITLE
Nueva página: evolución de la edad en el matrimonio

### ISSUE THREAD

**Issue by goiblas** [goiblas/open-data-la-rioja#24]
Crea nueva página en la sección de **Demografía** mostrando un gráfico con la evolución de la edad con que la gente se casa.

Los datos se pueden obtener de [https://web.larioja.org/dato-abierto/datoabierto?n=opd-54](https://web.larioja.org/dato-abierto/datoabierto?n=opd-54)

**Comment by Gabriel-ghub** [comment]
Jesús, buenas!

Me pongo a desarrollar esta nueva página.

Un saludo!
