### ISSUE TITLE
Nueva página: edad de defunción

### ISSUE THREAD

**Issue by goiblas** [goiblas/open-data-la-rioja#26]
Crea nueva página en la sección de **Demografía** mostrando un gráfico con la evolución de la edad de defunción.

Los datos se pueden obtener de [https://web.larioja.org/dato-abierto/datoabierto?n=opd-51](https://web.larioja.org/dato-abierto/datoabierto?n=opd-51)

**Comment by Gabriel-ghub** [comment]
I take this one!
