### ISSUE TITLE
Añadir la funcionalidad de obtener ingresos por categoría

### ISSUE THREAD

**Issue by goiblas** [goiblas/open-data-la-rioja#37]
En el fichero `src/lib/incomes.ts` falta añadir la funcionalidad de `getIncomesByCategory()`

Para probar la funcionalidad hay un test creado en `src/lib/incomes.test.ts` llamado 'should get incomes by category formatted' para ejecutarlo, lanza los test con `npm run test` y cambio `test.skip(...` por `test(...`

**Comment by ibaiway** [comment]
Hola @goiblas , tengo una duda. 

Si una categoria en alguno de los años su valor es = 0. Deberia de incluirse tambien o se excluye esa categoria para ese año?

**Opcion 1:**

  ``` 
[
    {
      "Impuestos Directos": 46222145.88,
      "Tasas Y Otros Ingresos.": 300,
      "year": 2001,
    },
    {
     "Impuestos Directos": 0,
      "Tasas Y Otros Ingresos.": 200,
      "year": 2002,
    },
]
```

**Opcion 2:**

  ``` 
[
    {
      "Impuestos Directos": 46222145.88,
      "Tasas Y Otros Ingresos.": 300,
      "year": 2001,
    },
    {
      "Tasas Y Otros Ingresos.": 200,
      "year": 2002,
    },
]
```

**Comment by goiblas** [comment]
Gracias por el interés, la idea es utilizar esos datos para pintar un gráfico de este tipo:
![image](https://github.com/goiblas/open-data-la-rioja/assets/4056962/4691fe13-2bd0-439f-9360-21da95c14ddf)

Creo que las 2 opciones nos pueden servir pero creo que prefiero la opción 2, ya que sobre todo en gastos cada año varía mucho la categorización

**Comment by ibaiway** [comment]
De acuerdo, veo a ver si soy capaz de sacarlo como aparece en la opcion 2. 
Concuerdo contigo en que para ese tipo de grafico tiene mas sentido.
