### ISSUE TITLE
add Prettier configuration

### ISSUE THREAD

**Issue by ibaiway** [goiblas/open-data-la-rioja#51]
I wonder if a prettier configuration file should be added, so that when people contribute there is a common style.

https://prettier.io/docs/en/configuration.html

**Comment by goiblas** [comment]
It may be a good idea, but I've had conflicts in the past between eslint and prettier. could you add it?

**Comment by goiblas** [comment]
Added! in the end it was easier than I thought, thanks for the suggestion
